import {
  attribute,
  autoGeneratedHashKey,
  hashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { Activities } from "src/api/infrastructure/interfaces/activity.interface";
import { BaseDocument } from "./baseDocument";

const TABLE_NAME = "hmg-activities";

@table(TABLE_NAME)
export class ActivityDocument extends BaseDocument implements Activities {
  public static tableName = TABLE_NAME;

  @autoGeneratedHashKey()
  @hashKey({
    indexKeyConfigurations: {
      ItemIdIndex: "HASH",
    },
  })
  id: string;

  @attribute()
  name: string;

  @attribute()
  value: number;

  public build(id: string, name: string, value: number): void {
    this.id = id;
    this.name = name;
    this.value = value;
  }
}
