import {
  attribute,
  autoGeneratedHashKey,
  hashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { ActivitiesSchedule } from "../interfaces/activitiesSchedule.interface";
import { BaseDocument } from "./baseDocument";

const TABLE_NAME = "hmg-activities-schedules";

@table(TABLE_NAME)
export class ActivitiesScheduleDocument
  extends BaseDocument
  implements ActivitiesSchedule
{
  public static tableName = TABLE_NAME;

  @autoGeneratedHashKey()
  @hashKey({
    indexKeyConfigurations: {
      ItemIdIndex: "HASH",
    },
  })
  id: string;

  @attribute()
  duration: number;

  @attribute()
  freequency: number;

  @attribute()
  scheduleId: string;

  @attribute()
  activityId: string;

  @attribute()
  name: string;

  @attribute()
  dailyBase: number;

  @attribute()
  parcialTime: number;
  public build(
    id: string,
    duration: number,
    freequency: number,
    scheduleId: string,
    activityId: string
  ): void {
    this.id = id;
    this.duration = duration;
    this.freequency = freequency;
    this.scheduleId = scheduleId;
    this.activityId = activityId;
  }
}
