import {
  attribute,
  autoGeneratedHashKey,
  hashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { Client } from "src/api/infrastructure/interfaces/client.interface";
import { BaseDocument } from "./baseDocument";

const TABLE_NAME = "hmg-clients";

@table(TABLE_NAME)
export class ClientDocument extends BaseDocument implements Client {
  public static tableName = TABLE_NAME;

  @autoGeneratedHashKey()
  @hashKey({
    indexKeyConfigurations: {
      ItemIdIndex: "HASH",
    },
  })
  id: string;
  @attribute()
  name: string;
  @attribute()
  birthDate: Date;
  @attribute()
  weight: number;
  @attribute()
  height: number;
  @attribute()
  phone: string;
  @attribute()
  userId: string;
  @attribute()
  gender: string;
  @attribute()
  factorHarris: number;
  @attribute()
  factorFAO: number;
  @attribute()
  factorMifflin: number;
  public build(
    id: string,
    name: string,
    birthDate: Date,
    weight: number,
    height: number,
    phone: string,
    userId: string,
    gender: string
  ): void {
    this.id = id;
    this.name = name;
    this.birthDate = birthDate;
    this.weight = weight;
    this.height = height;
    this.phone = phone;
    this.userId = userId;
    this.gender = gender;
  }
}
