import {
  attribute,
  autoGeneratedHashKey,
  hashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { Client } from "src/api/infrastructure/interfaces/client.interface";
import { BaseDocument } from "./baseDocument";

const TABLE_NAME = "hmg-clients";

@table(TABLE_NAME)
export class ClientDocument extends BaseDocument implements Client {
  public static tableName = TABLE_NAME;

  @autoGeneratedHashKey()
  @hashKey({
    indexKeyConfigurations: {
      ItemIdIndex: "HASH",
    },
  })
  id: string;

  @attribute()
  userId: string;

  @attribute()
  name: string;

  @attribute()
  birthDate: Date;

  @attribute()
  gender: string;

  public build(id, userId, name, birthDate, gender): void {
    this.id = id;
    this.userId = userId;
    this.name = name;
    this.birthDate = birthDate;
    this.gender = gender;
  }
}
