import {
  attribute,
  autoGeneratedHashKey,
  hashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { User } from "src/api/infrastructure/interfaces/user.interface";
import { Roles } from "../constants/roles";
import { Schedule } from "../interfaces/schedule.interface";
import { BaseDocument } from "./baseDocument";

const TABLE_NAME = "hmg-schedules";

@table(TABLE_NAME)
export class ScheduleDocument extends BaseDocument implements Schedule {
  public static tableName = TABLE_NAME;

  @autoGeneratedHashKey()
  @hashKey({
    indexKeyConfigurations: {
      ItemIdIndex: "HASH",
    },
  })
  id: string;

  @attribute()
  clientId: string;

  @attribute()
  activityId;

  @attribute()
  timeInHours: number;

  @attribute()
  activityDate: Date;

  @attribute()
  createdAt: Date;

  public build(
    id,
    clientId,
    timeInHours,
    activityId,
    activityDate,
    createdAt
  ): void {
    this.id = id;
    this.clientId = clientId;
    this.timeInHours = timeInHours;
    this.activityId = activityId;
    this.activityDate = activityDate;
    this.createdAt = createdAt;
  }
}
